## HYPOTHESIS TESTING ASSIGNMENTS 


Q.NO:1
A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.

Minitab File : Cutlets.mtw!


SOLUTION

As per given question we can find that it is the two sampled test 
Let us assume 

Null hypothesis as Ho:μ1 = μ2 (there is no difference between diameter of the cutlet)

Alternate hypothesis as Ha::μ1 ≠ μ2 (there is significant difference in diameters of cutlets)

In [1]:
import pandas as pd 
import numpy as np 
import warnings
warnings.filterwarnings("ignore")
from scipy import stats

In [5]:
df=pd.read_csv("Cutlets.csv")

In [6]:
df

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [10]:
df["Unit A"].mean()


7.0190914285714285

In [11]:
df["Unit B"].mean()

6.964297142857142

In [38]:
ztest,p=stats.ttest_ind(df["Unit A"],df["Unit B"])

In [45]:
p

0.4722394724599501

In [44]:
ztest

0.7228688704678063

In [39]:
print("zcalculated value is",ztest.round(3))
print("p-value is ",p.round(3))

zcalculated value is 0.723
p-value is  0.472


In [40]:
if p<0.05:
    print("reject null hypothesis , accept alternative hypothesis")
else:
    print("accept null hypothesis , reject alternative hypothesis")

accept null hypothesis , reject alternative hypothesis


In [46]:
# As null hypothesis is accepted so we can say that the diameter of the cutlets are significantly same


Q.NO:2

A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
  Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5%  
  significance level.
  
  Minitab File: LabTAT.mtw


SOLUTION:
 As the given question consists of multiple data sets we will  use ANOVA (3 sample test )
Null hypothesis as Ho:μ1 = μ2 =μ3 =μ4(there is no difference in average turn around TAT)

Alternate hypothesis as Ha::μ1 ≠ μ2 ≠ μ3 ≠ μ3(there is atleast one difference between report)

In [47]:
import pandas as pd 
import numpy as np 
import warnings
warnings.filterwarnings("ignore")
from scipy import stats

In [49]:
df1=pd.read_csv("LabTAT.csv")
df1

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [50]:
t1=df1["Laboratory 1"]
t2=df1["Laboratory 2"]
t3=df1["Laboratory 3"]
t4=df1["Laboratory 4"]

In [51]:
t1

0      185.35
1      170.49
2      192.77
3      177.33
4      193.41
        ...  
115    178.49
116    176.08
117    202.48
118    182.40
119    182.09
Name: Laboratory 1, Length: 120, dtype: float64

In [56]:
Fcalc,p=stats.f_oneway(t1,t2,t3,t4)

p


2.1156708949992414e-57

In [57]:
if p < 0.05:
    print("Ho is rejected and Ha is accepted")
else:
    print("Ho is rejected and Ha is rejected")

Ho is rejected and Ha is accepted


Ha alternative hypothesis is accepted thus atleast one sample TAT report is differnet 

Q.NO:3

Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.


solution:

As per given problem consists of categorical data we will use Chi square test 
let as assume Ho= male and female buyers ration is not same

and Ha = Male and female buyers ratio is same across the regions 

In [58]:
from scipy import stats 
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [59]:
df2=pd.read_csv("BuyerRatio.csv")

In [60]:
df2

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [62]:
df_table = df2.iloc[:,1:6]
df_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [79]:
df_table.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [80]:
stat,p_val,dof,expected = chi2_contingency([[50,142,131,70],[435,1523,1356,750]])

In [81]:
print(stat)
print(p_val)
print(dof)
print(expected)

1.595945538661058
0.6603094907091882
3
[[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [82]:
alpha = 0.05
prob=1-alpha
critical = chi2.ppf(prob,dof)
print('probability=%.3f,critical=%.3f,stat=%.3f'%(prob,critical,stat))
if stat >=critical:
    print("Ho is rejected and Ha is accepted")
else:
    print("Ho is accepted and Ha is rejected")

probability=0.950,critical=7.815,stat=1.596
Ho is accepted and Ha is rejected


In [83]:
if p_val<= alpha:
    print("Ho is rejected and Ha is accepted")
else:
    print("Ho is accepted and Ha is rejected")

Ho is accepted and Ha is rejected


In [84]:
#Hence in buyer ratio Ho is accepted and Ha is rejected so we can conclude that male and female buyer ratio is not same 

Q.NO:4


 TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

Minitab File: CustomerOrderForm.mtw
 


soution:
    
As per given problem consists of categorical data we will use Chi square test

Let as assume Ho = all the countries has same defective % 
 and Ha = alleast one country have more defective % 

In [85]:
df3=pd.read_csv("Costomer+OrderForm.csv")

In [86]:
df3

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [87]:
df3.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [95]:
df3["Phillippines"].value_counts(),df3["Indonesia"].value_counts(),df3["Malta"].value_counts(),df3["India"].value_counts()

(Error Free    271
 Defective      29
 Name: Phillippines, dtype: int64,
 Error Free    267
 Defective      33
 Name: Indonesia, dtype: int64,
 Error Free    269
 Defective      31
 Name: Malta, dtype: int64,
 Error Free    280
 Defective      20
 Name: India, dtype: int64)

In [74]:
observed =([29,33,31,20],[271,267,269,280])

In [75]:
observed

([29, 33, 31, 20], [271, 267, 269, 280])

In [89]:
stat1,p_val1,dof1,expected1 =chi2_contingency(observed)

In [90]:
print(stat1)
print(p_val1)
print(dof1)
print(expected1)

3.858960685820355
0.2771020991233135
3
[[ 28.25  28.25  28.25  28.25]
 [271.75 271.75 271.75 271.75]]


In [92]:
alpha = 0.05
prob1=1-alpha
critical = chi2.ppf(prob1,dof1)
print('probability=%.3f,critical=%.3f,stat=%.3f'%(prob1,critical,stat1))
if stat >=critical:
    print("Ho is rejected and Ha is accepted")
else:
    print("Ho is accepted and Ha is rejected")

probability=0.950,critical=7.815,stat=3.859
Ho is accepted and Ha is rejected


In [93]:
if p_val<= alpha:
    print("Ho is rejected and Ha is accepted")
else:
    print("Ho is accepted and Ha is rejected")

Ho is accepted and Ha is rejected


In [94]:
# as p-value 0.277>0.05 is high hence accept null hypothesis 
#percentage defective in all countries are equalinterences:
#as defective percentage is same in all countries there is no need of action